FROM mcr.microsoft.com/dotnet/nightly/sdk:10.0

RUN curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --runtime dotnet --channel 8.0 --install-dir /usr/share/dotnet \
    && curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --runtime dotnet --channel 9.0 --install-dir /usr/share/dotnet

WORKDIR /src

COPY . .

RUN dotnet restore

ENTRYPOINT ["dotnet", "test", "--no-restore", "--logger:console;verbosity=detailed"]
