name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
          
      - name: Run Build
        run: dotnet build src/ABSmartly.Sdk
        
      - name: Run Tests
        run: dotnet test tests/ABSmartly.Sdk.Tests
